apiVersion: v1
kind: Service
metadata:
  name: {{ include "merchant-portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "merchant-portal.name" . }}
    helm.sh/chart: {{ include "merchant-portal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.containerHttpPort }} 
      nodePort: {{ .Values.service.httpNodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "merchant-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
