apiVersion: v1
kind: Service
metadata:
  name: "ssh{{ include "merchant-portal.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "merchant-portal.name" . }}
    helm.sh/chart: {{ include "merchant-portal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshPort }}
      nodePort: {{ .Values.service.sshNodePort }}
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ include "merchant-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
